# Generated by Django 5.1.4 on 2024-12-20 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Полное название валюты')),
                ('short_name', models.CharField(max_length=3, verbose_name='Буквенный код')),
                ('symbol', models.TextField(blank=True, max_length=1, null=True, verbose_name='symbol')),
                ('flag', models.ImageField(blank=True, default=None, null=True, upload_to='products/thumbnails/images/', verbose_name='Картинка валюты в формате svg')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'ordering': ('short_name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_rate', models.DecimalField(decimal_places=6, max_digits=999, verbose_name='Курс обмена')),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('source_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rate_source', to='currencies.currency', verbose_name='исходная валюта')),
                ('target_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rate_target', to='currencies.currency', verbose_name='целевая валюта')),
            ],
            options={
                'verbose_name': 'курс обмена',
                'verbose_name_plural': 'курсы обмена',
                'ordering': ('from_date', 'source_currency'),
            },
        ),
    ]
