# Generated by Django 5.1.4 on 2024-12-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.TextField(blank=True, max_length=15, null=True, verbose_name='symbol'),
        ),
    ]
