# Generated by Django 5.1.4 on 2024-12-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_alter_currency_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='flag',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='currencies/flags/images/', verbose_name='Картинка валюты в формате svg'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.TextField(blank=True, max_length=15, null=True, verbose_name='Код символа валюты в формате HTML'),
        ),
    ]
